help_desk/help_desk/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('__debug__/', include('debug_toolbar.urls')),

]

help_desk/main/urls.py
from django.urls import path, re_path, include

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.main_page, name='main_page'),
    path('test/', views.test, name='test'),
    path('tickets/<int:ticket_id>/', views.ShowTicket.as_view(), name='show_ticket'),
    path('tickets/<int:ticket_id>/update_status', views.UpdateTicketStatus.as_view(), name='update_ticket_status'),
    path('tickets/create/', views.CreateTicket.as_view(), name='create_ticket'),
    path('accounts/login/', views.HelpDeskLoginView.as_view(), name='login_page'),
    path('accounts/logout/', views.HelpDeskLogoutView.as_view(), name='logout_page'),
    path('account/signup/', views.signup_page, name='signup_page'),
    path('accounts/useraccount/<int:pk>/',  views.UserAccountView.as_view(), name='user_account'),
    path('accounts/useraccount/<int:pk>/tickets_list/', views.UserAccountTicketsListView.as_view(), name='user_account_tickets_list'),
    path('accounts/useraccount/<int:pk>/profile_info', views.UserAccountProfileInfoEditView.as_view(), name='user_account_profile_info'),
    re_path(r'^media/.+', views.check_file_permissions, name='check_file_permissions'),
    path('500/', views.http_response_server_error, name='http_500'),
]

help_desk/main/forms.py
from django.forms import ModelForm, Textarea, HiddenInput, inlineformset_factory, Form, FileField
from django.core.exceptions import ValidationError
from django import forms
from django.contrib.auth.models import User
from django.core.validators import FileExtensionValidator


from .models import Ticket, Comment, UserProfile, File
from .widgets import TextareaBootstrap, TextInputBootstrap, SelectBootstrap, ClearableFileInputBootstrap, \
    EmailFieldBootstrap, PasswordInputBootstrap
from .services import del_profile_avatar
from .validators import FileValidator


class TicketForm(ModelForm):
    class Meta:
        model = Ticket
        fields = ['title', 'text', 'category', 'priority', 'author']
        widgets = {
            'text': TextareaBootstrap(placeholder='Describe your problem'),
            'title': TextInputBootstrap(placeholder='Brief describe of your problem'),
            'category': SelectBootstrap(),
            'priority': SelectBootstrap(),
            'author': HiddenInput()
        }
        labels = {
            'title': 'Theme',
            'author': 'Author'
        }


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['text', 'ticket', 'user']
        widgets = {
            'text': TextareaBootstrap(placeholder='Enter your message')
        }


class UploadFileForm(ModelForm):
    class Meta:
        model = File
        fields = ['file']
        widgets = {
            'file': ClearableFileInputBootstrap()
        }


class ProfileAvatarUploadFileForm(forms.Form):
    file = forms.FileField(required=False, validators=[FileValidator(content_types=('image/png', 'image/jpeg'),
                                                                     max_size=1024 * 1024)])

    def save(self, avatar, user):
        del_profile_avatar(user=user)
        file = File.objects.create(file=avatar, file_name=avatar.name, file_size=avatar.size,
                                   content_object=user.user_profile)
        return file

    class Meta:
        widgets = {
            'file': ClearableFileInputBootstrap()
        }


class SignupForm(forms.Form):
    username = forms.CharField(max_length=50, widget=TextInputBootstrap(placeholder='Enter username'))
    email = forms.EmailField(widget=EmailFieldBootstrap(placeholder='Enter you e-mail address'))
    password_1 = forms.CharField(max_length=30, widget=PasswordInputBootstrap(placeholder='Enter you password'))
    password_2 = forms.CharField(max_length=30, widget=PasswordInputBootstrap(placeholder='Repeat you password'))

    def clean_username(self):
        username = self.cleaned_data['username']
        try:
            user = User.objects.get(username=username)
        except User.DoesNotExist:
            return username
        raise forms.ValidationError('User with this name is already registered', code='user_already_exists')

    def clean_email(self):
        email = self.cleaned_data['email']
        try:
            email = User.objects.get(email=email)
        except User.DoesNotExist:
            return email
        raise forms.ValidationError('The specified email is already registered', code='email_already_exists')

    def clean(self):
        password_1 = self.cleaned_data['password_1']
        password_2 = self.cleaned_data['password_2']
        if password_1 != password_2:
            raise forms.ValidationError('Password mismatch', code='password_mismatch')
        return self.cleaned_data

    def save(self, *args, **kwargs):
        user = User.objects.create_user(username=self.cleaned_data['username'],
                                        email=self.cleaned_data['email'],
                                        password=self.cleaned_data['password_1'])
        return user


class UserProfileForm(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']
        widgets = {
            'username': TextInputBootstrap(attrs={
                'disabled': True
            }),
            'email': EmailFieldBootstrap(attrs={
                'disabled': True
            }),
            'first_name': TextInputBootstrap(placeholder='Enter your name'),
            'last_name': TextInputBootstrap(placeholder='Enter your last name')
        }


class UserProfileAdditionalForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = ['organization', 'city', 'position', 'phone']
        widgets = {
            'organization': TextInputBootstrap(placeholder='Enter the name of you organization'),
            'city': TextInputBootstrap(placeholder='Enter the name of your city'),
            'position': TextInputBootstrap(placeholder='Enter your position'),
            'phone': TextInputBootstrap(placeholder='Enter your contact phone number')
        }


class UpdateTicketStatusForm(ModelForm):
    class Meta:
        model = Ticket
        fields = ['priority', 'status']
        widgets = {
            'priority': SelectBootstrap(),
            'status': SelectBootstrap()
        }

help_desk/main/views.py
import os
import re
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404
from django.core.paginator import Paginator
from django.contrib.auth.models import User, Group
from django.http import HttpResponse, Http404
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.contrib.auth import views as auth_views
from django.views.generic import ListView
from django_sendfile import sendfile
from django.conf import settings
from guardian.shortcuts import assign_perm
from guardian.core import ObjectPermissionChecker
from django.core.exceptions import PermissionDenied
from django.db.models import Prefetch
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.base import View
import magic

from .models import News, Ticket, File, Comment, TicketCategory, TicketPriority
from .forms import TicketForm, UploadFileForm, CommentForm, SignupForm, UserProfileForm, UserProfileAdditionalForm,\
    ProfileAvatarUploadFileForm, UpdateTicketStatusForm
from .services import assign_ticket_and_file_perms


def test(request, *args, **kwargs):

    context = {
        'env': os.getenv('DJANGO_SETTINGS_MODULE'),
        'test_env': os.getenv('TEST_ENV')
    }

    return render(request, 'main/test.html', context)


def test_2(request, *args, **kwargs):
    am = User.objects.get(username='am')
    category = TicketCategory.objects.get(id=1)
    priority = TicketPriority.objects.get(id=1)
    for ticket in range(100):
        Ticket.objects.create(title='Тестовый тикет', text='Описание проблемы', author=am, category=category, priority=priority)
    return HttpResponse('OK')


def main_page(request, *args, **kwargs):
    all_news = News.objects.select_related('author').all()
    current_page_number = request.GET.get('page') or 1
    current_page_number = int(current_page_number)
    paginator = Paginator(all_news, 10)
    current_page = paginator.get_page(current_page_number)

    """
    page_range - генератор, содержащий набор номеров страниц, который передается в шаблон для формирования пагинатора.
    Стандартное поле Django paginator.page_range не используется целенаправленно, 
    чтобы избежать излишнего перебора по всему диапазону страниц и 
    необходимости реализации проверки условий в шаблоне (с целью не добавления логики проверки внутрь шаблона).
    В данном случае речь идет о количестве страниц, отображаемых в пагинаторе и проверке того, нужно ли
    отображать страницу из итератора paginator.page_range или нет.
    """
    page_range = (i for i in range(current_page_number - 3, current_page_number + 4)
                 if i >= 1 and i <= paginator.num_pages)

    context = {
        'current_page': current_page,
        'paginator': paginator,
        'current_page_number': current_page_number,
        'page_range': page_range
    }
    return render(request, 'main/index.html', context)


"""
@login_required
def create_ticket(request, *args, **kwargs):
    if request.method == 'POST':
        ticket_form_data = {
            'text': request.POST['text'],
            'title': request.POST['title'],
            'category': request.POST['category'],
            'priority': request.POST['priority'],
            'author': User.objects.get(username=request.user)
        }
        form = TicketForm(ticket_form_data)
        if form.is_valid():
            ticket = form.save()
            assign_perm(perm='view_ticket', user_or_group=request.user, obj=ticket)
            try:
                assign_perm(perm='view_ticket', user_or_group=Group.objects.
                            get(name=f'{ticket.category.codename}_admins'), obj=ticket)
            except Group.DoesNotExist as e:
                url = reverse('main:http_500')
                return HttpResponseRedirect(url)
            for file in request.FILES.getlist('file'):
                file_obj = File.objects.create(file=file, file_name=file.name, file_size=file.size,
                                               content_object=ticket)
                assign_perm(perm='view_file', user_or_group=request.user, obj=file_obj)
                try:
                    assign_perm(perm='view_file',
                                user_or_group=Group.objects.get(name=f'{ticket.category.codename}_admins'),
                                obj=file_obj)
                except Group.DoesNotExist as e:
                    url = reverse('main:http_500')
                    return HttpResponseRedirect(url)
            url = reverse('main:show_ticket', args=[ticket.id])
            return HttpResponseRedirect(url)

    else:
        form = TicketForm()
        file_form = UploadFileForm()

    context = {
        'form': form,
        'file_form': file_form
    }
    return render(request, 'main/add_ticket.html', context)
"""


class HelpDeskLoginView(auth_views.LoginView):
    template_name = 'main/signin.html'


class HelpDeskLogoutView(auth_views.LogoutView):
    pass


class CreateTicket(LoginRequiredMixin, View):
    template_name = 'main/add_ticket.html'

    def get(self, request, *args, **kwargs):
        form = TicketForm()
        file_form = UploadFileForm()

        context = {
            'form': form,
            'file_form': file_form
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        ticket_form_data = {
            'text': request.POST['text'],
            'title': request.POST['title'],
            'category': request.POST['category'],
            'priority': request.POST['priority'],
            'author': User.objects.get(username=request.user)
        }
        form = TicketForm(ticket_form_data)
        if form.is_valid():
            ticket = form.save()
            assign_ticket_and_file_perms(obj=ticket, user=request.user, perm='view_ticket',
                                         ticket=ticket)
            for file in request.FILES.getlist('file'):
                file_obj = File.objects.create(file=file, file_name=file.name, file_size=file.size,
                                               content_object=ticket)
                assign_ticket_and_file_perms(obj=file_obj, user=request.user, perm='view_file',
                                             ticket=ticket)
            url = reverse('main:show_ticket', args=[ticket.id])
            return HttpResponseRedirect(url)


"""
@login_required
def show_ticket(request, *args, **kwargs):
    ticket_id = kwargs['ticket_id']
    ticket_obj = get_object_or_404(Ticket.objects.select_related('author', 'category', 'priority', 'status').
                                   prefetch_related('files'), pk=ticket_id)
    perm_checker = ObjectPermissionChecker(request.user)
    if not perm_checker.has_perm('view_ticket', ticket_obj):
        raise PermissionDenied
    comments = Comment.objects.select_related('user').prefetch_related('files').filter(ticket=ticket_obj)

    if request.method == 'POST':
        comment_form_data = {
            'text': request.POST['text'],
            'ticket': ticket_id,
            'user': request.user
        }
        comment_form = CommentForm(comment_form_data)
        if comment_form.is_valid():
            comment = comment_form.save()
            for file in request.FILES.getlist('file'):
                file_obj = File.objects.create(file=file, file_name=file.name, file_size=file.size,
                                               content_object=comment)
                if request.user.id != ticket_obj.author.id:
                    assign_perm(perm='view_file', user_or_group=User.objects.get(id=ticket_obj.author.id), obj=file_obj)
                try:
                    assign_perm(perm='view_file',
                                user_or_group=Group.objects.get(name=f'{ticket_obj.category.codename}_admins'),
                                obj=file_obj)
                except Group.DoesNotExist as e:
                    url = reverse('main:http_500')
                    return HttpResponseRedirect(url)
        url = reverse('main:show_ticket', args=[kwargs['ticket_id']])
        return HttpResponseRedirect(url)
    else:
        comment_form = CommentForm()
        file_form = UploadFileForm()

        context = {
            'ticket': ticket_obj,
            'comment_form': comment_form,
            'file_form': file_form,
            'comments': comments
        }
    return render(request, 'main/show_ticket.html', context)
"""


class ShowTicket(LoginRequiredMixin, View):
    template_name = 'main/show_ticket.html'

    def setup(self, request, *args, **kwargs):
        super(ShowTicket, self).setup(request, *args, **kwargs)
        self.ticket_id = self.kwargs['ticket_id']
        self.ticket_obj = ticket_obj = get_object_or_404(Ticket.objects.select_related('author', 'category', 'priority', 'status').
                                   prefetch_related('files'), pk=self.ticket_id)
        self.comments = Comment.objects.select_related('user').prefetch_related('files').filter(ticket=self.ticket_obj)

    def dispatch(self, request, *args, **kwargs):
        perm_checker = ObjectPermissionChecker(request.user)
        if not perm_checker.has_perm('view_ticket', self.ticket_obj) and request.user.is_authenticated:
            raise PermissionDenied
        return super(ShowTicket, self).dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        comment_form = CommentForm()
        file_form = UploadFileForm()
        ticket_status_form = UpdateTicketStatusForm(instance=self.ticket_obj)

        context = {
            'ticket': self.ticket_obj,
            'comment_form': comment_form,
            'file_form': file_form,
            'comments': self.comments,
            'ticket_status_form': ticket_status_form
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        comment_form_data = {

help_desk/main/templates/main/add_ticket.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="container ticket_container" style="margin-top: 5em">
        {% for e in form.non_field_errors %}
            <div class="alert alert-dismissible alert-warning">
                <h4 class="alert-heading">Warning!</h4>
                <p class="mb-0">{{ e }}</p>
            </div>
        {% endfor %}

        {% for field in form %}
            {% if field.errors %}
                <div class="alert alert-dismissible alert-warning">
                    <h4 class="alert-heading">Warning!</h4>
                    <p class="mb-0">{{ field.errors }}</p>
                </div>
            {% endif %}
        {% endfor %}
        <div class="row ticket_description">
            <div class="col-12">
                <form method="post" action="" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="col-form-label">
                        {{ form.title.label }}
                    </div>
                    {{ form.title }}
                    <div class="col-form-label">
                        {{ form.text.label }}
                    </div>
                    {{ form.text }}
                    <div class="col-form-label">
                        {{ form.category.label }}
                    </div>
                    {{ form.category }}
                    <div class="col-form-label">
                        {{ form.priority.label }}
                    </div>
                    <div class="col-form-label">
                    {{ form.priority }}
                    </div>
                    <div class="col-form-label">
                        {{ file_form }}
                    </div>
            </div>
            <div class="form-actions">
                <button type="submit" class="btn btn-primary" style="margin-top: 5em">
                    Create ticket
                </button>
            </div>
            </form>
        </div>
    </div>
    </div>
{% endblock %}

help_desk/main/templates/main/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Help desk system</title>
    <link rel="stylesheet" href="{% static 'bootstrap/material_design/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'help_desk/css/help_desk.css' %}">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" href="{% url 'main:main_page' %}">Help desk</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01"
            aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'main:create_ticket' %}">Create ticket
                    <span class="sr-only">(current)</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Features</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Pricing</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">About</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true"
                   aria-expanded="false">Dropdown</a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <a class="dropdown-item" href="#">Something else here</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Separated link</a>
                </div>
            </li>
            <li class="nav-item active">
                {% if request.user.is_authenticated %}
                    <a class="nav-link" href= "{% url 'main:user_account' user.id %}"> {{ request.user }}
                    <span class="sr-only">(current)</span>
                    </a>
                {% else %}
                    <a class="nav-link" href="{% url 'main:login_page' %}">Sign in
                    <span class="sr-only">(current)</span>
                    </a>
                {% endif %}
            </li>
            {% if request.user.is_authenticated %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'main:logout_page' %}"> Sign out
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
            {% endif %}
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search">
            <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>

{% block content %} {% endblock %}

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js"
        integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF"
        crossorigin="anonymous"></script>
</body>
</html>

help_desk/main/templates/main/index.html
{% extends 'main/base.html' %}

{% block content %}
<div class="container news_container">
    {% for n in current_page %}
        <div class="row">
            <div class="col-12">
                <div class="card border-primary mb-3">
                    <div class="card-header" style="display: flex; justify-content: space-between"; >
                        <span> Технические работы </span>
                        <span> {{ n.added_at }}</span>
                    </div>
                    <div class="card-body">
                        <h4 class="card-title">{{ n.title }}</h4>
                        <p class="card-text"> {{ n.text }}</p>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% if paginator.num_pages >= 2 %}
        <div>
            <div class="row news_paginator">
                <div class="col-12">
                    <ul class="pagination pagination-lg">
                        {% if current_page.has_previous %}
                            <li class="page-item">
                                <a class="page-link"
                                   href="{% url 'main:main_page' %}?page={{ current_page.previous_page_number }}">&laquo;</a>
                            </li>
                        {% else %}
                            <li class="page-item disabled">
                                <a class="page-link"
                                   href="{% url 'main:main_page' %}?page={{ current_page_number }}">&laquo;</a>
                            </li>
                        {% endif %}
                        {% for num_page in page_range %}
                            {% if num_page == current_page_number %}
                                <li class="page-item active">
                                    <a class="page-link" href="{% url 'main:main_page' %}?page={{ num_page }}">{{ num_page }}</a>
                                </li>
                            {% else %}
                                <li class="page-item">
                                    <a class="page-link"
                                       href="{% url 'main:main_page' %}?page={{ num_page }}">{{ num_page }}</a>
                                </li>
                            {% endif %}
                        {% endfor %}
                        {% if current_page.has_next %}
                            <li class="page-item">
                                <a class="page-link"
                                   href="{% url 'main:main_page' %}?page={{ current_page.next_page_number }}">&raquo;</a>
                            </li>
                        {% else %}
                            <li class="page-item disabled">
                                <a class="page-link"
                                   href="{% url 'main:main_page' %}?page={{ current_page_number }}">&raquo;</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
{%  endif %}
</div>
{% endblock %}

help_desk/main/templates/main/show_ticket.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="jumbotron ticket_description">
                    <h1 class="display-5">{{ ticket.title }}</h1>
                    <div><strong>Creation date:</strong> {{ticket.added_at}}</div>
                    <div> <strong>Author:</strong> {{ ticket.author }}</div>
                    <div><strong>Category:</strong> {{ ticket.category }}</div>
                    <div> <strong> Ticket description:</strong> {{ticket.text}}</div>
                    <form method="post" action="{% url 'main:update_ticket_status' ticket.id%}" enctype="application/x-www-form-urlencoded">
                        {% csrf_token %}
                        <strong>{{ticket_status_form.priority.label}}</strong>{{ticket_status_form.priority}}
                        <strong>{{ticket_status_form.status.label}}</strong>{{ticket_status_form.status}}
                        <div class="form-actions">
                            <button type="submit" class="btn btn-primary" style="margin-top: 2em">
                                Update
                            </button>
                        </div>
                    </form>
                    <div class="ticket_attachments" style="display: flex; justify-content: flex-end">
                        {% for file in ticket.files.all %}
                            <span class="attached_file" style="margin-right: 1em">
                                <a href="{{ MEDIA_URL}}{{ file.file }}" download>
                                    <img src="/static/help_desk/images/file_pic.gif">
                                    <span>{{ file.file_name }} ({{ file.file_size | filesizeformat}})</span>
                                </a>
                            </span>
                        {% endfor %}
                    </div>
        </div>
            </div>
        </div>
        <div class="row comment_form" style="margin-bottom: 3em">
            <div class="col-12">
                <form method="post" action="" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ comment_form.text }}
                    {{ file_form.file }}
                    <div class="form-actions">
                        <button type="submit" class="btn btn-primary" style="margin-top: 2em">
                            Leave a message
                        </button>
                    </div>
                </form>
            </div>
        </div>
        {% for comment in comments.all %}
            <div class="row">
                <div class="col-12">
                    <div class="card border-primary mb-3">
                        <div class="card-header" style="display: flex; justify-content: space-between">
                            <span> {{ comment.user }} </span>
                            <span> Отправлено {{ comment.added_at }}</span>
                        </div>
                        <div class="card-body">
                            <p class="card-text">{{ comment.text }}</p>
                            <div class="comment_attachments" style="display: flex; justify-content: flex-end">
                            {% for file in comment.files.all %}
                                <span class="attached_file" style="margin-right: 1em">
                                    <a href="{{ MEDIA_URL}}{{ file.file }}" download>
                                        <img src="/static/help_desk/images/file_pic.gif">
                                        <span>{{ file.file_name }} ({{ file.file_size | filesizeformat}})</span>
                                    </a>
                                </span>
                            {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        {% endfor %}
    </div>
{% endblock %}

help_desk/main/templates/main/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Test</title>
</head>
<body>
<div>
    OK
</div>

<div>
    {{env}}
</div>
<div>
    {{test_env}}
</div>
</body>
</html>

help_desk/main/templates/main/user_account_page_base.html
{% extends 'main/base.html' %}

{% block content %}

<div class="container user_page_container">
    <div class="row">
        <div class="col-3 user_page_nav">
            <div class="list-group">
                <a href="{% url 'main:user_account_profile_info' request.user.id %}" class="list-group-item list-group-item-action">My profile</a>
                <a href="{% url 'main:user_account_tickets_list' request.user.id %}" class="list-group-item list-group-item-action">My tickets</a>
                <a href="#" class="list-group-item list-group-item-action disabled">Settings</a>
            </div>
        </div>
        {% block user_account_page_content %}
        {% endblock %}
    </div>
</div>


{% endblock %}